import { ENV_HEADER, serializeEnvFile } from "./env.mjs"
import { buildDatabaseEnv, buildDatabaseServiceEnv } from "../config/database.mjs"
import { buildStorageEnv, buildGarageServiceEnv } from "../config/storage.mjs"
import { buildRedisEnv } from "../config/redis.mjs"
import { composeEnvFor } from "./compose.mjs"

/**
 * The generated `.env`, assembled from the configuration.
 *
 * SECTIONED BY CONCERN rather than sorted, because this file is read by a
 * person changing one thing. Each section carries the note an operator needs at
 * the moment they are looking at it — not the full explanation, which lives in
 * `.env.example`, but the sentence that stops a wrong edit.
 *
 * Only what was CHOSEN appears. No commented-out alternatives: a generated
 * `.env` with three database URLs in it, two of them commented, is a file where
 * the authoritative one is a guess. `.env.example` is where alternatives are
 * documented, and it ships unchanged.
 */
export function buildEnvFile(config) {
  const { secrets } = config
  const isDocker = config.deploymentMode === "docker"

  const sections = [
    {
      title: "Database",
      notes: [
        "The dialect is explicit and is never inferred from the URL: MariaDB and",
        "MySQL share a URL scheme, so inference would run one engine's SQL",
        "against the other.",
      ],
      entries: Object.entries(buildDatabaseEnv(config)),
    },
    {
      title: "Secrets",
      notes: [
        "Generated by create-flowcms. Each is independent — one leaking does not",
        "compromise the others, and rotating one does not rotate the rest.",
        "",
        "AUTH_SECRET signs every session: whoever holds it can forge an",
        "administrator session. Rotating it signs everyone out, which is expected.",
        "Every replica must receive the SAME values.",
      ],
      entries: [
        ["AUTH_SECRET", secrets.authSecret],
        ["CAPTCHA_SECRET", secrets.captchaSecret],
        ["PREVIEW_SECRET", secrets.previewSecret],
      ],
    },
    {
      title: "First-run setup",
      notes: [
        "Gates the public /setup form. You need this value once, to create the",
        "first owner account; after setup completes, /setup returns 404 and this",
        "does nothing. It is never put in a URL.",
      ],
      entries: [["FLOWCMS_SETUP_TOKEN", secrets.setupToken]],
    },
    {
      title: "Application",
      notes: [
        "The admin panel's PUBLIC path. Change it and restart — the image is not",
        "rebuilt, and every link follows. A handful of first segments are",
        "reserved by the application and refused at startup.",
      ],
      entries: [
        ["FLOWCMS_ADMIN_PATH", config.adminPath],
        [isDocker ? "BASE_URL" : "NEXT_PUBLIC_BASE_URL", config.baseUrl],
        ...(isDocker ? [["FLOWCMS_PORT", String(config.port)]] : []),
      ],
    },
    {
      title: "Object storage (S3-compatible)",
      notes:
        config.storage === "garage"
          ? [
              "Pointing at the bundled Garage service on the Docker network. The",
              "browser never talks to it: images are served through",
              "/api/public/images and presigned URLs are generated server-side.",
            ]
          : [
              "Your S3-compatible provider. FlowCMS does not branch on vendor —",
              "AWS, R2, B2, Wasabi, Spaces and a self-hosted Garage all work",
              "through these five values.",
            ],
      entries: Object.entries(buildStorageEnv(config)),
    },
    {
      title: "Redis (optional)",
      notes: [
        "Absent means the in-process login rate limiter: still limiting, not",
        "coordinated across replicas. Enable it for more than one instance.",
      ],
      entries: Object.entries(buildRedisEnv(config)),
    },
    {
      title: "Managed service credentials",
      notes: [
        "Read by the database and storage CONTAINERS, not by FlowCMS. They are",
        "here so there is one source for each secret rather than a copy in",
        "compose.yml as well.",
      ],
      entries: [
        ...Object.entries(buildDatabaseServiceEnv(config)),
        ...Object.entries(buildGarageServiceEnv(config)),
      ],
    },
    {
      title: "Docker Compose",
      notes: [
        "Which Compose files and profiles this project uses, so `docker compose",
        "up -d` needs no flags. The path separator is pinned because Compose's",
        "default differs between platforms and this file is committed.",
      ],
      entries: Object.entries(composeEnvFor(config)),
    },
  ]

  return ENV_HEADER.join("\n") + serializeEnvFile(sections)
}
