/**
 * Derived mysql schema, as named exports.
 *
 * drizzle-kit introspects a module's exported table objects to generate
 * migrations, and it cannot see through a runtime-built object — hence the
 * explicit re-exports below. They are mechanical: one line per table, in the
 * same order as src/db/schema/index.ts, regenerated by scripts/gen-dialect-schema.mjs.
 *
 * The application never imports this file. It exists for the migration
 * generator; the running app derives the same tables through
 * src/db/createDatabase.ts.
 */
import * as sqliteSchema from "./schema"
import { deriveSchema } from "./deriveDialects"

const t = deriveSchema(sqliteSchema as Record<string, unknown>, "mysql")

export const users = t.users
export const accounts = t.accounts
export const sessions = t.sessions
export const verificationTokens = t.verificationTokens
export const blogCategories = t.blogCategories
export const blogTags = t.blogTags
export const authors = t.authors
export const blogPosts = t.blogPosts
export const blogPostCategories = t.blogPostCategories
export const blogPostTags = t.blogPostTags
export const blogPostFaqs = t.blogPostFaqs
export const blogPostRevisions = t.blogPostRevisions
export const blogPostLocks = t.blogPostLocks
export const blogSeries = t.blogSeries
export const blogPostRelated = t.blogPostRelated
export const blogPostQuestions = t.blogPostQuestions
export const businessReviews = t.businessReviews
export const notFoundLog = t.notFoundLog
export const linkCheckResults = t.linkCheckResults
export const redirects = t.redirects
export const settings = t.settings
export const activityLog = t.activityLog
export const searchConsoleIssues = t.searchConsoleIssues
export const customPages = t.customPages
export const menus = t.menus
export const menuItems = t.menuItems
export const themeSettings = t.themeSettings
