#!/usr/bin/env node
/**
 * A THROWAWAY `.env` FOR THE COMPOSE-BASED JOBS.
 *
 * `compose.yml` and the database overlays use Compose's `:?` guard on every
 * secret — AUTH_SECRET, the Garage keys, POSTGRES_PASSWORD, MYSQL_PASSWORD,
 * MARIADB_PASSWORD and the two root passwords. That guard is correct: it
 * refuses to start rather than silently defaulting a credential, and CI must
 * not be the reason somebody weakens it.
 *
 * So CI generates a whole `.env` instead. Every value in it is random, lives
 * for the length of one job, and is never written to a log.
 *
 * WHY THIS IS NOT THE SAME SCRIPT AS `generate-test-secrets.mjs`
 *
 * They solve different problems and the difference is not cosmetic.
 * `generate-test-secrets.mjs` writes to `$GITHUB_ENV`, which GitHub Actions
 * reads between steps — it can only ever configure the RUNNER. Compose reads a
 * `.env` FILE from the project directory before any step's environment exists,
 * and its service-level `environment:` blocks are interpolated at `up` time
 * from that file. One cannot substitute for the other.
 *
 * `.env` is gitignored (`.gitignore` ignores `.env` and `.env.*` and un-ignores
 * only the examples), so this cannot be committed by accident.
 *
 * Usage:
 *   node scripts/ci/write-ci-env.mjs                writes ./.env
 *   node scripts/ci/write-ci-env.mjs --print-keys   lists the keys, no values
 */

import { randomBytes } from "node:crypto"
import { existsSync, writeFileSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..")
const TARGET = join(ROOT, ".env")

const b64 = () => randomBytes(32).toString("base64")
// Alphanumeric for the database passwords. A base64 value can contain `/`, `+`
// and `=`, all of which need escaping inside a `postgresql://user:pass@host`
// URL — and the URLs in the compose overlays interpolate the password
// unescaped. This is a CI-only shape decision, not a strength decision:
// 32 alphanumeric characters is ~165 bits.
const alnum = () =>
  randomBytes(48)
    .toString("base64")
    .replace(/[^A-Za-z0-9]/g, "")
    .slice(0, 32)

/**
 * Every key the compose files guard with `:?`, plus the handful that make the
 * stack behave like a real deployment rather than a half-configured one.
 */
export function buildComposeEnvironment() {
  return {
    // --- application ---
    AUTH_SECRET: b64(),
    CAPTCHA_SECRET: b64(),
    PREVIEW_SECRET: b64(),
    FLOWCMS_SETUP_TOKEN: b64(),
    FLOWCMS_PORT: "3000",
    BASE_URL: "http://localhost:3000",
    FLOWCMS_ADMIN_PATH: "/admin",

    // --- bundled S3 (Garage) ---
    GARAGE_BUCKET: "flowcms",
    GARAGE_ACCESS_KEY_ID: randomBytes(16).toString("hex"),
    GARAGE_SECRET_ACCESS_KEY: b64(),

    // --- PostgreSQL overlay ---
    POSTGRES_USER: "flowcms",
    POSTGRES_DB: "flowcms",
    POSTGRES_PASSWORD: alnum(),

    // --- MySQL overlay ---
    MYSQL_DATABASE: "flowcms",
    MYSQL_USER: "flowcms",
    MYSQL_PASSWORD: alnum(),
    MYSQL_ROOT_PASSWORD: alnum(),

    // --- MariaDB overlay — a separate service with its own credentials, not an
    // alias of the MySQL block. Sharing them here would be the first step of
    // the "test MySQL twice and label one MariaDB" mistake the topology matrix
    // exists to prevent.
    MARIADB_DATABASE: "flowcms",
    MARIADB_USER: "flowcms",
    MARIADB_PASSWORD: alnum(),
    MARIADB_ROOT_PASSWORD: alnum(),
  }
}

const env = buildComposeEnvironment()

if (process.argv.includes("--print-keys")) {
  for (const key of Object.keys(env)) console.log(key)
  process.exit(0)
}

if (existsSync(TARGET) && !process.argv.includes("--force")) {
  // Refuse rather than overwrite. This script is meant for an ephemeral runner;
  // running it on a developer's machine must not destroy their configuration.
  console.error(
    `Refusing to overwrite ${TARGET}.\n` +
      "This script writes a throwaway CI environment and is not meant to run on a\n" +
      "machine that already has one. Pass --force if you are certain.",
  )
  process.exit(1)
}

const body =
  "# Generated by scripts/ci/write-ci-env.mjs for one CI job.\n" +
  "# Every value is random and ephemeral. Nothing here is a real credential,\n" +
  "# and nothing here is reused between jobs or between runs.\n\n" +
  Object.entries(env)
    .map(([k, v]) => `${k}=${v}`)
    .join("\n") +
  "\n"

writeFileSync(TARGET, body, { mode: 0o600 })

// Names only. Printing a value would defeat the whole arrangement, and CI logs
// are readable by anyone who can read the repository.
console.log(`Wrote ${Object.keys(env).length} ephemeral values to .env (values not shown).`)
