/**
 * WHAT A GENERATED FLOWCMS PROJECT CONTAINS.
 *
 * An allowlist, not "the repository minus some ignores". The difference matters
 * more than it looks: an ignore list ships everything nobody thought to
 * exclude, and this repository contains a developer's `.env`, a SQLite
 * database, a credentials scratch file, Docker volume state, agent tooling and
 * several thousand lines of internal planning. Every one of those is a file
 * that would have to be *remembered*. An allowlist ships what somebody wrote
 * down, and a new directory is absent by default.
 *
 * The builder fails when an entry names something that no longer exists, so a
 * moved directory is a build error rather than a project missing a feature.
 */

/**
 * Directories copied whole, minus EXCLUDE below.
 *
 * `src` carries the whole application — every dialect, both storage paths, the
 * admin-path indirection, the first-run setup domain. Phase 7.3 removes none of
 * it: the scaffolder chooses nothing, so it may delete nothing.
 */
export const DIRECTORIES = [
  "src",
  "public",
  "scripts",
  "docker",
  // The public theme API, carried as a local package. `flowcms` is not
  // published yet, so a generated project cannot depend on a registry version —
  // and must not depend on a path back into this repository. See D4 in
  // dev-docs/superpowers/specs/2026-08-24-create-flowcms-scaffolder-design.md.
  "packages/flowcms",
]

/** Single files, each named on purpose. */
export const FILES = [
  "package.json",
  "tsconfig.json",
  // The package build's project file. `scripts/build-package.mjs` names it, so
  // a generated project without it has a script that cannot run.
  "tsconfig.package.json",
  "next.config.ts",
  // `next-env.d.ts` is NOT here, and must not be added back. Next generates it,
  // Next's own shipped documentation says twice not to track it, `.gitignore`
  // honours that, and the copy in this repository imports
  // `./.next/types/routes.d.ts` — build output. A FILES entry for it names a
  // file no fresh clone has, which fails the template build (and therefore
  // `npm test`) for everybody except the person who last ran `next build`.
  // `src/next-globals.d.ts` carries the two ambient references instead, and
  // ships automatically because `src` is a DIRECTORIES entry copied whole.
  "postcss.config.mjs",
  "eslint.config.mjs",
  "components.json",
  ".env.example",
  ".dockerignore",
  // LINE ENDINGS, which decide whether the operator's container starts.
  //
  // Git for Windows installs with `core.autocrlf=true`, so a generated project
  // that was committed and then cloned on Windows gets a CRLF
  // `docker/entrypoint.sh` — and the kernel then looks for the interpreter
  // `/bin/sh\r` and the container exits reporting that a path which obviously
  // exists does not. `.gitattributes` is what stops that, and it is only worth
  // having here if it travels with the template.
  //
  // Unlike `.gitignore` this needs no rename: npm rewrites a packed
  // `.gitignore`, and nothing else.
  ".gitattributes",
  "Dockerfile",
  "compose.yml",
  "compose.dev.yml",
  "compose.external-s3.yml",
  "compose.postgres.yml",
  "compose.mysql.yml",
  "compose.mariadb.yml",
  // Operator- and theme-author-facing.
  //
  // NOTHING GOVERNING *THIS* REPOSITORY BELONGS BELOW. CONTRIBUTING,
  // SECURITY, CODE_OF_CONDUCT and CHANGELOG, and the maintainer documents in
  // dev-docs/, describe developing FlowCMS, not running a site. `.github/` is
  // the same thing in another shape: issue templates that route bug reports to the
  // FlowCMS maintainers, a pull-request checklist about this codebase's
  // conventions, and release workflows for this repository's packages. A
  // generated project is somebody else's site — shipping it a conduct policy
  // to enforce, or an issue form pointing at our tracker, is nonsense, and a
  // workflow that publishes our packages from their CI is worse than nonsense.
  //
  // None of them is listed here, and `tests/scaffolder/template.test.ts` fails
  // if one ever reaches the template by another route.
  "docs/docker.md",
  "docs/setup/first-run.md",
  "docs/themes/authoring.md",
]

/**
 * Copied to a different name.
 *
 * npm rewrites a `.gitignore` inside a published package, so a template that
 * shipped one would arrive missing it and every generated project would commit
 * `node_modules` on its first push. Stored neutrally, renamed by the CLI.
 */
export const RENAMED = [{ from: ".gitignore", to: "gitignore" }]

/**
 * Paths excluded from the directories above, with the reason each one is not
 * simply an oversight.
 */
export const EXCLUDE = [
  // 9.8 MB of editor assets, gitignored, regenerated by `postinstall`.
  // Shipping them would triple the tarball to deliver a stale copy.
  "public/assets/tinymce",

  // Development sample data, and Bun-only. The generated project drops the
  // `db:seed` script with it.
  "src/db/seed.ts",

  // The in-tree theme-switching fixture. Registered only under
  // FLOWCMS_INTEGRATION_THEMES, and an operator's Appearance screen should not
  // contain a test theme at all. `registry.ts` carries a template-strip for the
  // import that would otherwise dangle.
  "src/Themes/integration",

  // Repository verification, not application code.
  "scripts/build-example-theme.mjs",
  "scripts/verify-package-consumer.mjs",
  "scripts/verify-create-flowcms.mjs",
  "scripts/build-create-flowcms.mjs",
  "scripts/lib/templateManifest.mjs",
  "scripts/db-matrix.sh",
  // The package-manager matrix proof. It packs THIS repository's
  // `create-flowcms`, installs it under four managers and scaffolds from it —
  // none of which means anything inside a generated site, which has no
  // scaffolder to pack.
  "scripts/verify-package-manager-matrix.mjs",

  // CI AND RELEASE TOOLING FOR THIS REPOSITORY, added in Phase 8.
  //
  // All four reach a generated project the same way every other script does:
  // `scripts` is a DIRECTORIES entry copied WHOLE, so a new file there ships by
  // default and is absent only once somebody writes it down here. None of them
  // means anything in a generated site — they assert THIS repository's lockfile
  // and theme tracing, mint secrets for THIS repository's CI, and prove and
  // version-sync a release of OUR packages, which a generated project does not
  // publish. Verified before excluding: nothing the template keeps imports any
  // of them, and no generated `package.json` script, `Dockerfile` line or
  // `docker/entrypoint.sh` line names one.
  "scripts/ci",
  "scripts/verify-artifact-hygiene.mjs",
  "scripts/release-proof.mjs",
  "scripts/release-version-sync.mjs",

  // THE LOCAL CORE DEVELOPMENT WORKFLOW — this repository only.
  //
  // `scripts/dev/` orchestrates `dev:docker` and `dev:reset` from the HOST: it
  // generates a developer's local secrets, resolves this project's Docker
  // volumes and resets the database between first-run tests. Every one of those
  // is an activity of developing FlowCMS itself. A generated project is a site,
  // not a fork — its operator gets a real `.env` written by create-flowcms and
  // has no reason to regenerate one, and a `dev:reset` shipped to somebody's
  // actual installation is a command that deletes their content.
  //
  // `scripts/dev-container-start.mjs` is NOT excluded and must not be: it is
  // the `command:` in `compose.dev.yml`, which every generated project DOES
  // ship, and it carries the migrate-before-serve fix into those projects too.
  // The prefix rule here matches `scripts/dev/` only — `scripts/dev` is not a
  // prefix of `scripts/dev-container-start.mjs` under `entry + separator`.
  "scripts/dev",

  "docker/storage-roundtrip.test.ts",
  "docker/storage-persistence.test.ts",

  // Release tooling for THIS repository's copy of the package. A generated
  // project's copy is a local `file:` dependency that is never published, so a
  // publish guard there would refer to release blockers the operator has
  // nothing to do with. The `prepublishOnly` script that names it is removed
  // from the generated package's manifest alongside it.
  "packages/flowcms/publish-guard.mjs",

  // Generated output that must never be copied.
  "packages/flowcms/dist",
]

/**
 * Files whose `flowcms:template-strip` blocks are removed on the way out.
 *
 * Each entry MUST match at least once — a sentinel somebody deleted or renamed
 * fails the build here rather than producing a generated project that cannot
 * compile. The blocks exist because the theme registry is static by design:
 * a fixture cannot be left out of a copy without also removing the import that
 * names it.
 */
export const STRIPPED = [
  // The example theme package: its import, its registry entry, its screenshot.
  "src/Themes/packages.ts",
  // The integration theme's import and registry entry.
  "src/Themes/registry.ts",
  // The `@source` line registering the example theme's dist with Tailwind.
  "src/app/globals.css",
  // Its manifest COPY and its build step.
  "Dockerfile",
  // The scaffolder's own build output, which means nothing in a generated
  // project. Stripped on the way through the rename below.
  ".gitignore",
]

/**
 * Written by the builder rather than copied, because their content in a
 * generated project is genuinely different from their content here.
 */
export const GENERATED = ["README.md"]

/**
 * Scripts removed from the generated `package.json`, and why.
 *
 * Every remaining script is checked by `tests/scaffolder/generatedProject...`
 * to reference a file the template actually contains — the classic scaffolder
 * defect being a `package.json` full of commands that point at files the
 * template left behind.
 */
export const DROPPED_SCRIPTS = {
  test: "the suite asserts against this repository's own fixtures and packaging",
  "test:watch": "same",
  // The host half of the Core development workflow — see `scripts/dev` in
  // EXCLUDE. The container half (`scripts/dev-container-start.mjs`) ships, so
  // `docker compose -f compose.yml -f compose.dev.yml up` still migrates before
  // it serves in a generated project; only the convenience wrapper is dropped.
  "dev:docker": "local Core development tooling; scripts/dev is not shipped",
  "dev:docker:build": "same",
  "dev:reset": "same — and a reset command that deletes a live site's database has no business in one",
  "db:seed": "development sample data; src/db/seed.ts is not shipped",
  "build:example-theme": "the example theme is not shipped",
  "build:template": "it builds create-flowcms's own template; the script is not shipped",
  // Generating migrations is FlowCMS development, not site operation, and there
  // is one command per dialect because there is one Drizzle config per dialect
  // (MariaDB shares the MySQL track). None of the three configs is shipped —
  // `tests/scaffolder/template.test.ts` fails if a `drizzle.config.*` ever
  // reaches a generated project — so any script naming one has to go with them.
  "db:generate:sqlite": "generating migrations is FlowCMS development, not site operation",
  "db:generate:postgresql": "same",
  "db:generate:mysql": "same — MariaDB shares this track",
  "db:studio:sqlite": "the schema browser names a drizzle.config the template does not ship",
  "db:studio:postgresql": "same",
  "db:studio:mysql": "same — MariaDB shares this track",
}

/** Dependencies removed from the generated `package.json`, and why. */
export const DROPPED_DEV_DEPENDENCIES = {
  "@example/flowcms-theme-aurora": "the example theme is a repository fixture",
  vitest: "the test suite is not shipped",
  "drizzle-kit": "only the db:generate:* and db:studio:* scripts used it, and all six are dropped",
}

/** Scripts whose command changes because part of it referenced a fixture. */
export const REWRITTEN_SCRIPTS = {
  "build:packages": "node scripts/build-package.mjs",
}
