/**
 * Paths this app refuses to let an admin claim for a redirect or a custom
 * page. Not load-bearing for routing correctness — Next always resolves a
 * more specific static/dynamic route ahead of the root `[...path]` catch-all
 * regardless of what's in the database — but a row saved under one of these
 * would silently never fire, and that's worse than refusing it outright.
 */

/** First path segment that would collide with an existing top-level route. */
export const RESERVED_FIRST_SEGMENTS = ["admin-panel", "api", "blog", "preview", "sitemap"] as const

/** Whole-path routes generated by Next's file conventions (robots.ts,
 *  sitemap.ts, sitemap-index.xml, the static favicon). */
export const RESERVED_EXACT_PATHS = ["/robots.txt", "/favicon.ico", "/sitemap.xml", "/sitemap-index.xml"] as const

/**
 * @param adminRoot The configured public admin path, when the caller knows it.
 *   The admin namespace always wins over a custom page: precedence has to be
 *   deterministic and independent of creation order, and the failure direction
 *   matters — a refused page is a message, whereas a page that shadowed the
 *   control panel would lock an operator out of the only screen that could
 *   undo it. Optional so callers with no config in scope keep working.
 */
export function isReservedPath(path: string, adminRoot?: string): boolean {
  if ((RESERVED_EXACT_PATHS as readonly string[]).includes(path)) return true
  if (adminRoot && (path === adminRoot || path.startsWith(`${adminRoot}/`))) return true
  const firstSegment = path.split("/").filter(Boolean)[0]
  return firstSegment ? (RESERVED_FIRST_SEGMENTS as readonly string[]).includes(firstSegment) : false
}
