/**
 * THE LOCAL CORE DEVELOPMENT ENVIRONMENT — generated once, reused forever.
 *
 * This module exists so that developing FlowCMS Core does not begin with
 * twenty minutes of copying `.env.example` and pasting `openssl rand` output.
 * It generates the credentials a working local installation needs, stores them
 * in a gitignored file, and hands them to Docker Compose.
 *
 * WHAT IT DOES NOT DO, AND MUST NEVER DO
 *
 * It does not weaken anything. Every value it generates is 32 cryptographically
 * random bytes and satisfies `Framework/Config/deploymentSecret.ts` on that
 * file's own terms — there is no development bypass, no relaxed floor, and no
 * placeholder. `FLOWCMS_SETUP_TOKEN` in particular stays REAL: it is generated,
 * printed to the developer's terminal, and then demanded by the `/setup` form
 * exactly as it would be on a production install. The convenience is in the
 * tooling; the security model is untouched.
 *
 * WHY A SEPARATE FILE RATHER THAN WRITING TO `.env`
 *
 * `.env` is the developer's, and it is also what a local *production-topology*
 * `docker compose up` reads. A tool that edits it owns a file it did not write.
 * `.env.dev.local` is unambiguous: everything in it was generated by this
 * module, deleting it costs nothing but a regeneration, and it never competes
 * with a hand-written value — see the precedence rule below.
 *
 * WHY THE VALUES ARE PASSED THROUGH THE CHILD PROCESS ENVIRONMENT
 *
 * Compose resolves `${VAR}` from two places: the process environment, and a
 * `.env` file in the project directory — process environment first. Passing
 * `--env-file .env.dev.local` would NOT layer on top of that, it would REPLACE
 * the default `.env` loading outright, silently discarding whatever the
 * developer has configured there. Handing the merged values to the `docker
 * compose` child process instead composes correctly with `.env` and needs no
 * flag at all.
 *
 * PRECEDENCE, highest first:
 *
 *   1. the real shell environment  — an explicit export always wins
 *   2. `.env`                      — the developer's own configuration
 *   3. `.env.dev.local`            — generated, and only ever fills gaps
 *
 * So a key that already exists anywhere above is never generated and never
 * overwritten. That is what keeps an existing local instance working: the
 * Garage credentials in a developer's `.env` already match the data in their
 * `garage-data` volume, and rotating them would strand it.
 */

import { randomBytes } from "node:crypto"
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"

/** The repository root, from this file's location rather than `process.cwd()`. */
export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..")

/** The generated file's name. Referenced by `.gitignore` and `.dockerignore`. */
export const LOCAL_ENV_FILENAME = ".env.dev.local"
export const LOCAL_ENV_PATH = join(ROOT, LOCAL_ENV_FILENAME)
export const ENV_PATH = join(ROOT, ".env")

/**
 * base64url, matching `packages/create-flowcms/src/secrets.mjs`.
 *
 * Not plain base64: `+`, `/` and `=` are all characters that have to survive a
 * `.env` file, a Compose interpolation and a copy-paste into a browser form
 * without being escaped, quoted or trimmed by something along the way. 32 bytes
 * is 256 bits either way.
 */
const SECRET_BYTES = 32
const secret = () => randomBytes(SECRET_BYTES).toString("base64url")

/**
 * Garage's access key id: 32 hex characters, the shape
 * `scripts/ci/write-ci-env.mjs` already generates and Garage already accepts.
 */
const accessKeyId = () => randomBytes(16).toString("hex")

/**
 * Every variable this module will generate, why it is needed, and whether the
 * application judges it as a deployment secret.
 *
 * AUDITED AGAINST THE RUNNING TOPOLOGY rather than assumed. `AUTH_SECRET` is
 * the only one Compose guards with `:?` — the rest fail later and more quietly,
 * which is precisely why they belong here:
 *
 *   AUTH_SECRET               Compose refuses to start without it.
 *   CAPTCHA_SECRET            Absent, no login challenge can be issued or
 *                             verified, so the admin panel is unreachable.
 *                             Reported through /api/ready, not at boot.
 *   FLOWCMS_SETUP_TOKEN       Absent, the /setup form is LOCKED — the exact
 *                             wall this environment was built to get past.
 *   PREVIEW_SECRET            Absent, shareable draft previews are disabled.
 *                             Optional in production; generated here because a
 *                             development install should exercise every path.
 *   GARAGE_ACCESS_KEY_ID      Absent, Garage starts with no default key and the
 *   GARAGE_SECRET_ACCESS_KEY  storage prerequisite reports not_configured, so
 *                             the setup page cannot be satisfied and no upload
 *                             works. Not `:?`-guarded, deliberately — see the
 *                             comment on the garage service in compose.yml.
 */
export const MANAGED_VARIABLES = [
  {
    key: "AUTH_SECRET",
    generate: secret,
    deploymentSecret: true,
    purpose: "signs every session token",
  },
  {
    key: "CAPTCHA_SECRET",
    generate: secret,
    deploymentSecret: true,
    purpose: "signs the login CAPTCHA challenge",
  },
  {
    key: "FLOWCMS_SETUP_TOKEN",
    generate: secret,
    deploymentSecret: true,
    purpose: "authorizes the web first-run form at /setup",
  },
  {
    key: "PREVIEW_SECRET",
    generate: secret,
    deploymentSecret: true,
    purpose: "signs shareable draft preview links",
  },
  {
    key: "GARAGE_ACCESS_KEY_ID",
    generate: accessKeyId,
    deploymentSecret: false,
    purpose: "the bundled object storage's access key",
  },
  {
    key: "GARAGE_SECRET_ACCESS_KEY",
    generate: secret,
    deploymentSecret: false,
    purpose: "the bundled object storage's secret key",
  },
]

// ---------------------------------------------------------------------------
// Secret policy — a deliberate, tested duplicate
// ---------------------------------------------------------------------------

/**
 * The application's secret policy, restated for a plain-Node script.
 *
 * `Framework/Config/deploymentSecret.ts` is TypeScript behind the `@/` alias
 * and cannot be imported here, which is the same constraint
 * `scripts/migrate.mjs` faces with `databaseConfig.ts` — and this file answers
 * it the same way that one does: restate the rules, then pin the two together
 * with a parity test. `tests/dev/devSecretPolicy.test.ts` runs a table of
 * inputs through both and fails if they ever disagree, so the duplication
 * cannot drift into two different ideas of what counts as a secret.
 *
 * Nothing below is a relaxed development variant. If this module and the
 * application ever disagree, the test fails and the application is right.
 */
export const MIN_SECRET_LENGTH = 24
export const MIN_SECRET_DISTINCT_CHARS = 8

const PLACEHOLDER_MARKERS = [
  "changeme",
  "change-me",
  "change_me",
  "replace-me",
  "replace_me",
  "replaceme",
  "your-secret",
  "your_secret",
  "your-setup-token",
  "your_setup_token",
  "setup-token-here",
  "secret-here",
  "placeholder",
  "example",
  "insecure",
  "password",
  "xxxxxxxx",
  "default",
]

const SHORT_PLACEHOLDER_MARKERS = ["todo"]

const containsDelimited = (lowered, marker) =>
  new RegExp(`(^|[^a-z0-9])${marker}([^a-z0-9]|$)`).test(lowered)

/**
 * Judge a value without ever reproducing it. Mirrors `classifyDeploymentSecret`.
 *
 * Returns `{ state: "missing" | "unsafe" | "usable", reason }`, and `reason`
 * names the RULE that was broken, never the string that broke it — a message
 * quoting a secret has moved that secret into a terminal scrollback, a
 * screenshot and, eventually, an issue.
 */
export function classifyLocalSecret(configured) {
  const value = (configured ?? "").trim()

  if (value.length === 0) return { state: "missing", reason: null }

  if (value.length < MIN_SECRET_LENGTH) {
    return { state: "unsafe", reason: `it must be at least ${MIN_SECRET_LENGTH} characters` }
  }

  if (new Set(value).size < MIN_SECRET_DISTINCT_CHARS) {
    return {
      state: "unsafe",
      reason:
        `it must contain at least ${MIN_SECRET_DISTINCT_CHARS} distinct characters ` +
        "— generate a random value rather than a repeated pattern",
    }
  }

  const lowered = value.toLowerCase()
  const looksLikePlaceholder =
    PLACEHOLDER_MARKERS.some((marker) => lowered.includes(marker)) ||
    SHORT_PLACEHOLDER_MARKERS.some((marker) => containsDelimited(lowered, marker))

  if (looksLikePlaceholder) {
    return {
      state: "unsafe",
      reason: "it looks like a placeholder from the documentation — generate a random value",
    }
  }

  return { state: "usable", reason: null }
}

/**
 * Generate until the application would accept it.
 *
 * Not paranoia, and not theoretical: the placeholder denylist matches
 * substrings, and a random value can contain one. `secretGeneration.test.ts`
 * documents exactly that happening — a generated secret containing `todo`,
 * roughly once in a few hundred CI runs, rejected as a placeholder. That case
 * was fixed by anchoring the marker, but the general shape remains: a denylist
 * over random strings has a collision rate above zero.
 *
 * Rejecting and redrawing costs microseconds and removes the failure mode
 * entirely. The bound exists so that a future policy change which makes every
 * value unacceptable fails loudly here instead of hanging.
 */
export function generateAcceptable(generate, attempts = 100) {
  for (let attempt = 0; attempt < attempts; attempt++) {
    const value = generate()
    if (classifyLocalSecret(value).state === "usable") return value
  }
  throw new Error(
    "Could not generate a value the secret policy accepts after " +
      `${attempts} attempts. classifyLocalSecret() and the generator disagree.`,
  )
}

// ---------------------------------------------------------------------------
// env files
// ---------------------------------------------------------------------------

/**
 * A deliberately small `.env` parser: `KEY=value`, one per line.
 *
 * No dependency, because this runs before anything is installed in some of the
 * situations it has to work in, and no interpolation, because a value here is a
 * literal credential and expanding `$` inside one would corrupt it.
 */
export function parseEnvText(text) {
  const values = {}
  for (const rawLine of String(text).split(/\r?\n/)) {
    const line = rawLine.trim()
    if (line === "" || line.startsWith("#")) continue

    const match = /^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/.exec(line)
    if (!match) continue

    let value = match[2].trim()
    if (
      (value.startsWith('"') && value.endsWith('"') && value.length >= 2) ||
      (value.startsWith("'") && value.endsWith("'") && value.length >= 2)
    ) {
      value = value.slice(1, -1)
    }
    values[match[1]] = value
  }
  return values
}

/** Parse an env file, or `{}` when it does not exist. */
export function readEnvFile(path) {
  if (!existsSync(path)) return {}
  return parseEnvText(readFileSync(path, "utf8"))
}

/** An unset variable and an empty one mean the same thing here: not configured. */
const isSet = (value) => typeof value === "string" && value.trim() !== ""

/**
 * Resolve every managed variable across the three layers, generating whatever
 * is still missing and appending only the new values to `.env.dev.local`.
 *
 * IDEMPOTENT BY CONSTRUCTION. A key that resolves from any layer is left
 * exactly as it is, so a second run generates nothing and a hundredth run
 * generates nothing. Secrets do not rotate on restart, which is what lets
 * `dev:reset` wipe the database while the setup token a developer has in their
 * clipboard stays valid.
 */
export function ensureLocalEnvironment({
  shellEnv = process.env,
  envPath = ENV_PATH,
  localPath = LOCAL_ENV_PATH,
  // Injectable so the test suite can exercise resolution without writing a file
  // into the repository root. Nothing about the DEFAULT path is conditional on
  // being under test — the real callers use the real writer.
  persist = true,
} = {}) {
  const fromEnv = readEnvFile(envPath)
  const fromLocal = readEnvFile(localPath)

  const values = {}
  const sources = {}
  const generated = []

  for (const variable of MANAGED_VARIABLES) {
    const { key } = variable

    // Precedence, highest first. Documented at the top of this file, and the
    // reason a developer's own `.env` is never fought with.
    if (isSet(shellEnv[key])) {
      values[key] = shellEnv[key]
      sources[key] = "shell"
    } else if (isSet(fromEnv[key])) {
      values[key] = fromEnv[key]
      sources[key] = ".env"
    } else if (isSet(fromLocal[key])) {
      values[key] = fromLocal[key]
      sources[key] = LOCAL_ENV_FILENAME
    } else {
      values[key] = variable.deploymentSecret
        ? generateAcceptable(variable.generate)
        : variable.generate()
      sources[key] = "generated"
      generated.push(key)
    }
  }

  if (persist && generated.length > 0) {
    writeLocalEnv(localPath, {
      ...fromLocal,
      ...Object.fromEntries(generated.map((key) => [key, values[key]])),
    })
  }

  return { values, sources, generated }
}

/**
 * Rewrite `.env.dev.local` from scratch, carrying forward anything already in
 * it. Mode 0600 where the platform honours it; Windows ignores the bit and
 * relies on the user's profile ACL, which is the same protection `.env` has.
 */
function writeLocalEnv(path, values) {
  const body =
    `# ${LOCAL_ENV_FILENAME} — generated by scripts/dev/localEnv.mjs.\n` +
    "#\n" +
    "# LOCAL CORE DEVELOPMENT ONLY. Every value here is random, belongs to this\n" +
    "# machine, and is never committed: .gitignore and .dockerignore both name\n" +
    "# this file explicitly. Delete it to have a fresh set generated; that\n" +
    "# invalidates existing sessions and orphans the bundled storage's data,\n" +
    "# so prefer `npm run dev:reset` when you only want a fresh installation.\n" +
    "#\n" +
    "# Values already present in `.env` or the shell are NOT duplicated here —\n" +
    "# this file only ever fills gaps.\n" +
    "\n" +
    Object.entries(values)
      .map(([key, value]) => `${key}=${value}`)
      .join("\n") +
    "\n"

  writeFileSync(path, body, { mode: 0o600 })
}

/**
 * Resolve a variable this module does not manage, through the same layers.
 *
 * For display only — `FLOWCMS_PORT` and `FLOWCMS_ADMIN_PATH` are not secrets
 * and Compose reads them perfectly well on its own. The banner needs them
 * because it prints URLs, and a banner that says `localhost:3000` to somebody
 * who set `FLOWCMS_PORT=8080` in their `.env` is worse than no banner: it sends
 * them to a port nothing is listening on and it looks like the stack is broken.
 */
export function resolveUnmanaged(key, fallback, { shellEnv = process.env } = {}) {
  const layers = [shellEnv[key], readEnvFile(ENV_PATH)[key], readEnvFile(LOCAL_ENV_PATH)[key]]
  return layers.find(isSet) ?? fallback
}

/**
 * Check every managed deployment secret against the policy, whatever layer it
 * came from.
 *
 * Generated values are acceptable by construction, so in practice this judges
 * what a developer put in their own `.env` — and it refuses rather than
 * silently overriding it. Overwriting a value somebody typed on purpose is a
 * worse outcome than stopping to say which rule it broke.
 */
export function validateSecrets({ values, sources }) {
  const problems = []
  for (const variable of MANAGED_VARIABLES) {
    if (!variable.deploymentSecret) continue
    const verdict = classifyLocalSecret(values[variable.key])
    if (verdict.state === "usable") continue
    problems.push({
      key: variable.key,
      source: sources[variable.key],
      // Never the value. See classifyLocalSecret.
      reason: verdict.reason ?? "it is not set",
    })
  }
  return problems
}
