import { describe, expect, it } from "vitest"
import { existsSync, readFileSync } from "node:fs"
import { join } from "node:path"
import { DIRECTORIES, FILES } from "../../scripts/lib/templateManifest.mjs"

/**
 * THE TEMPLATE MANIFEST MUST DESCRIBE A CLONE, NOT A DEVELOPER'S DISK.
 *
 * `scripts/build-create-flowcms.mjs` fails when a manifest entry names
 * something that does not exist. That is the right behaviour and it is not
 * enough, because "exists" is evaluated against whatever happens to be sitting
 * in the working directory. A file that is git-ignored, or a directory whose
 * only contents are generated, exists on the machine of everybody who has ever
 * run a build here and is absent from a fresh clone — so the manifest passes
 * for the maintainers and fails for the first contributor, in a build step
 * nobody runs until release day.
 *
 * Two entries were in exactly that state before this test existed:
 *
 *   next-env.d.ts   git-ignored at .gitignore, and listed in FILES. Next's own
 *                   documentation is unambiguous — project-structure.md calls
 *                   it a file that "should not be tracked by version control"
 *                   and config/typescript.md says "We recommend adding
 *                   next-env.d.ts to your .gitignore file". Next regenerates it
 *                   on the next `next dev` or `next build`, and the copy on
 *                   disk here even references `./.next/types/routes.d.ts`,
 *                   which is build output. It is not a source file and it must
 *                   not be shipped as one.
 *
 *   public/         named in DIRECTORIES with nothing tracked inside it. Its
 *                   only content was `public/assets/tinymce`, which is
 *                   git-ignored, created by `postinstall`, and excluded from
 *                   the template anyway.
 *
 * These assertions are deliberately narrow and textual. A full "would git
 * ignore this?" oracle means shelling out to git from the test suite, and the
 * suite is Node-first and runs in places where that is not a safe assumption.
 * A literal `.gitignore` line match catches the shape both defects had, which
 * is a whole file named outright.
 */

const ROOT = process.cwd()

/**
 * Literal, non-negated `.gitignore` lines — the ones that name a file outright
 * rather than describing a pattern. Nothing here interprets `*`, `/` anchoring
 * or directory semantics; a pattern rule simply is not checked.
 */
const IGNORED_LITERALS = new Set(
  readFileSync(join(ROOT, ".gitignore"), "utf8")
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("#") && !line.startsWith("!"))
    .filter((line) => !/[*?[\]]/.test(line) && !line.includes("/")),
)

describe("the template manifest names nothing a fresh clone lacks", () => {
  it("lists no git-ignored file in FILES", () => {
    const offenders = FILES.filter((entry: string) => {
      const basename = entry.split("/").pop() as string
      return IGNORED_LITERALS.has(basename) || IGNORED_LITERALS.has(entry)
    })

    // If this fails on `next-env.d.ts`, the fix is to delete the manifest
    // entry, NOT to un-ignore the file. See the header.
    expect(offenders).toEqual([])
  })

  it("does not ship next-env.d.ts", () => {
    expect(FILES).not.toContain("next-env.d.ts")
  })

  it("keeps next-env.d.ts git-ignored, as Next.js documents", () => {
    // The pair matters more than either half: a manifest that stopped naming
    // the file and a `.gitignore` that stopped ignoring it would both look
    // reasonable in isolation and would put a build artefact into git.
    expect(IGNORED_LITERALS.has("next-env.d.ts")).toBe(true)
  })
})

describe("every directory the manifest copies survives a clone", () => {
  it("public/ carries a tracked placeholder for as long as it is a manifest entry", () => {
    if (!DIRECTORIES.includes("public")) return

    // `public/` is empty in this repository — the marketing site it used to
    // hold is gone, the favicon lives at src/app/favicon.ico under the App
    // Router convention, and robots.txt is generated by src/app/robots.ts. It
    // stays a manifest entry because operators drop their own static files
    // into it, and it needs one tracked file so that a clone has the directory
    // at all.
    //
    // A tracked `public/robots.txt` would NOT do instead: Next serves `public/`
    // ahead of the App Router, so a static file of that name would silently
    // shadow the generated route.
    expect(existsSync(join(ROOT, "public", ".gitkeep"))).toBe(true)
    expect(IGNORED_LITERALS.has(".gitkeep")).toBe(false)
  })
})
